name = "tunnel-quiz"
compatibility_date = "2026-07-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "tunnel-quiz"
database_id = "08f52117-8cd1-4546-9393-58c071860ff9"

[vars]
FROM_EMAIL = "The Tunnel & Quiz <bookings@tunnelpubquiz.com>"
TABLE_LIMIT = "12"
